### ISSUE TITLE
error on running toulligQC

### ISSUE THREAD

**Issue by AssiaSaltykova** [GenomicParisCentre/toulligQC#1]
When running toulligQC, i'm getting the following error: 
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
and running setup.py with --inplace --force does not solve it

**Comment by jourdren** [comment]
Hi,

Could-you send me your system configuration (OS, Python and Numpy version...) and your command line to see the origin of the issue ?

Laurent.

**Comment by AssiaSaltykova** [comment]
Hey
It's:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Python 3.5.2
Numpy 1.13.1

Thanks!

**Comment by jourdren** [comment]
Hi,

Our intern who wrote ToulligQC code chose to use the latest dependency versions (Python 3.6, NumPy 1.12, pandas 0.19, matplotlib 2.0, seaborn 0.7 and h5py 0.7) for ToulligQC development. So, it is actually quite difficult to install ToulligQC on an Ubuntu version lower than 17.04. Many graphs generated by ToulligQC require the latest features of ToulligQC's dependencies, so it should be very painful to switch back to older versions of dependencies. As ToulligQC is our first big pure Python project  with many dependencies, we did not pay attention to this during the project development. :-(

I recommend you to use Ubuntu 17.04, a virtualenv with the right ToulligQC dependencies version or the easiest solution: our Docker image (genomicpariscentre/toulligqc:latest) that works as we use it for all our MinION runs.

Best regards,

Laurent.

**Comment by BasBerbers** [comment]
I tried to use the docker image and I got an error about the sample sheet. I didn't include a sample sheet, because I have non bar-coded samples.

This is the command line I used and the error:

$ docker run -ti \
> --rm \
> -v /path/to/result/directory:/data/bas/toulligqc/ \
> -v /path/to/fast5/directory:/data/bas/basecalled2-3557-BB4/workspace/pass/ \
> -v /path/to/fastq/directory:/data/bas/basecalled2-3557-BB4/merged_fastq/pass/3557-basecalled-BB4-new.fastq.gz \
> -v /path/to/sequencing/summary/file:/data/bas/basecalled2-3557-BB4/sequencing_summary.txt \
> genomicpariscentre/toulligqc:latest -n test_bas -f /data/bas/basecalled2-3557-BB4/workspace/pass/ -a /data/bas/basecalled2-3557-BB4/sequencing_summary.txt -q /data/bas/basecalled2-3557-BB4/merged_fastq/pass/3557-basecalled-BB4-new.fastq.gz -o /data/bas/toulligqc/
Traceback (most recent call last):
  File "/usr/local/bin/toulligqc", line 11, in <module>
    load_entry_point('toulligqc===-0.1a1-', 'console_scripts', 'toulligqc')()
  File "/usr/local/lib/python3.5/dist-packages/toulligqc-_0.1a1_-py3.5.egg/toulligqc/toulligqc.py", line 229, in main
    check_conf(config_dictionary)
  File "/usr/local/lib/python3.5/dist-packages/toulligqc-_0.1a1_-py3.5.egg/toulligqc/toulligqc.py", line 142, in check_conf
    if not config_dictionary['sample_sheet_file']:
  File "/usr/local/lib/python3.5/dist-packages/toulligqc-_0.1a1_-py3.5.egg/toulligqc/toulligqc_conf.py", line 46, in __getitem__
    return self._config_dictionary[item]
KeyError: 'sample_sheet_file'

**Comment by jourdren** [comment]
Hi,

I've just fixed the issue (barcoding option was always on). You can update your docker image with the following command and then relaunch your QC:

`$ docker pull genomicpariscentre/toulligqc:latest`

Best regards,

Laurent.

**Comment by BasBerbers** [comment]
Hi,

Thank you very much! Toulligqc worked now with the docker image. It worked very fast and was also easy to use once I understood how docker worked.
However, I was wondering if it is possible to use Toulligqc on a subset of fastq files. With Albacore 2.0.2 you can filter out low quality reads. Toulligqc still gives the statistics of all reads when the input is only the passed fastq files. 

Bas

**Comment by jourdren** [comment]
Hi,

Great to know that ToulligQC now works on your system!

You cannot currently use ToulligQC on a subset of FASTQ files but you can use only one file as source of FASTQ files.

We plan to support Albacore 2.0.2 in the next weeks and then 1D square runs.

Laurent.

**Comment by AssiaSaltykova** [comment]
Dear Laurent,
Thanks for the quick answers and fixes, everything is working fine for us now! 
Kind regards
Assia
