### ISSUE TITLE
Run toulligQC error

### ISSUE THREAD

**Issue by gligong** [GenomicParisCentre/toulligQC#3]
Ok, I tried our barcoded nanopore data, and toulligqc generated reports. So, for non bar coded data, what can I do because tougligqc requires sample sheet file?

It gives KeyError: 'sample_sheet_file'
Thanks!

George

I am trying to run toulligQC to generate albacore run reports. I tried different options, and always got errors. It looks like that toulligqc requires all the options even when the run does not have barcodes.
I ran following cammand:
toulligqc -n test_run \
      -f /storage/FILES/Oxford_Minion/Hudson_Sept8_FLO-MIN106_SQK-LSK108/Sept_R9.4_flowcells/testReport/0 \
      -a /storage/FILES/Oxford_Minion/Hudson_Sept8_FLO-MIN106_SQK-LSK108/Sept_R9.4_flowcells/testReport/ \
      -q /storage/FILES/Oxford_Minion/Hudson_Sept8_FLO-MIN106_SQK-LSK108/Sept_R9.4_flowcells/testReport/fastq \
      -o /storage/FILES/Oxford_Minion/Hudson_Sept8_FLO-MIN106_SQK-LSK108/Sept_R9.4_flowcells/testReport/report
and got following errors:
Traceback (most recent call last):
  File "/home/apps/toulligQC/toulligQC-20170912/bin/toulligqc", line 11, in <module>
    load_entry_point('toulligqc===-0.1a1-', 'console_scripts', 'toulligqc')()
  File "/home/apps/toulligQC/toulligQC-20170912/lib/python3.6/site-packages/toulligqc-_0.1a1_-py3.6.egg/toulligqc/toulligqc.py", line 229, in main
    check_conf(config_dictionary)
  File "/home/apps/toulligQC/toulligQC-20170912/lib/python3.6/site-packages/toulligqc-_0.1a1_-py3.6.egg/toulligqc/toulligqc.py", line 142, in check_conf
    if not config_dictionary['sample_sheet_file']:
  File "/home/apps/toulligQC/toulligQC-20170912/lib/python3.6/site-packages/toulligqc-_0.1a1_-py3.6.egg/toulligqc/toulligqc_conf.py", line 46, in __getitem__
    return self._config_dictionary[item]
KeyError: 'sample_sheet_file'

 I am wondering if you could show me how to run toulligqc with following output from an Albacore run. The pass directory has 0, 1, 2 sub directories holding fast5 files. Fastq files are also in the pass directory.
Thanks!

George

albacoreResults\
-----      configuration.cfg
-----      pipeline.log
-----      sequencing_summary.txt
-----      workspace\
------             fail\
------             pass\
---------                  0\
---------                  1\
---------                  2\
---------                  fastq_runid_31ee3c191ce764f50a56b1bbee67326bf4c6d40e_0.fastq
---------                  fastq_runid_31ee3c191ce764f50a56b1bbee67326bf4c6d40e_1.fastq
---------                  fastq_runid_77317b2780c17bc6d729717e91f58ff31823c8a8_2.fastq

**Comment by jourdren** [comment]
Hi,

I've just fixed the issue (barcoding option was always on) with the "8377072" commit. Please update your ToulligQC Git repository with a `git fetch origin master && git pull` and then reinstall ToulligQC.

Best regards,

Laurent.
