### ISSUE TITLE
Make available via bioconda?

### ISSUE THREAD

**Issue by mjafin** [GenomicParisCentre/toulligQC#4]
Hi there,
Thanks for a very interesting software package. I was wondering if you're still actively developing this whether you would consider making this available via bioconda?

Thanks,
Miika

**Comment by jourdren** [comment]
Dear mjafin,

We released today the first official version of ToulligQC (0.4) and we made it available on the PyPi repository [1]. We are considering making our software available via Bioconda, however as we never used Bioconda we need to learn how to package and submitting Bioconda recipes.

Moreover, a Docker image for ToulligQC is already available on the Docker hub [2].

Best regards,

Laurent.

[1] https://pypi.org/project/toulligqc/
[2] https://hub.docker.com/r/genomicpariscentre/toulligqc/

**Comment by mjafin** [comment]
Nice one, thanks for the PyPi package.
